### ISSUE TITLE
prettytable not installed by default

### ISSUE THREAD

**Issue by srbrown13** [jbmcfarlin31/python-math-quiz#1]
Might want to add a requirements.txt file with the required imports listed.  Or update the readme file with something like:  
>python -m pip install prettytable --proxy=myproxy:80

**Comment by jbmcfarlin31** [comment]
The README includes the `pip install...` command for PrettyTable - but I have also included a `requirements.txt` file for the import as well. Other imports will go into the requirements file and can be installed like so:
`pip install -r requirements.txt`
